import React from "react";

import { SplitWrap, SplitItem } from "../../components/SplitComp";
import {
  Navbar,
  Footer,
  Section,
  ContentContainer,
} from "../../components/layout";
import WhiteBoxes from "./components/WhiteBoxes";
import Hero from "./components/Hero";
import Technologies from "./components/Technologies";

import BgImgSubscriber from "../../components/Subscriber/BgImgSubscriber";
import subscriberbgImg from "../../assets/img/subscribers-digialidentity.png";
import SectionBgImg from "../../assets/img/backgrounds/sectionbg.png";
import profileimg from "../../assets/img/explain-profile.png";
import hiveimg from "../../assets/img/explain-hive.png";

const VerifiedCredentialPage = () => {
  return (
    <>
      <Navbar navColor="dark" />
      <main>
        <Hero
          title="A better way to be online"
          intro="Having multiple profiles is messy. Your personal information is copied and stored on every app. Profile gives you total control of your digital world, in one place. Finally unlock the power of your content online."
        />
        <WhiteBoxes />
        <Technologies />

        <ContentContainer>
          <SplitWrap>
            <div className="features-split-inner section-inner">
              <div className="split-wrap">
                <SplitItem
                  imgSrc={profileimg}
                  title="A new type of digital identity owned by you"
                  description="Profile gives you total control over your digital world all in one place. Finally unlock the power of your data and digital content."
                />
              </div>
            </div>
          </SplitWrap>
        </ContentContainer>

        <Section
          containerStyle={{
            background: `url(${SectionBgImg})`,
          }}
          padding="138px 11% 138px"
          bgColor="rgb(76, 111, 255, .8)"
          txtColor="white"
          txtStyle={{
            color: "white",
            fontSize: "25px",
            lineHeight: "35px",
          }}
          contentText="Centralized social media applications and online platforms exist today because the data generated by users holds immense value. Profile denies such intrusion by permitting users to create their own self-sovereign identities, unlocking platform features such as personal data storage. This is the only platform of its kind in existence today."
        />
        <ContentContainer>
          <SplitWrap className="mt-5">
            <div className="features-split-inner section-inner">
              <div className="split-wrap">
                <SplitItem
                  imgSrc={hiveimg}
                  title="Own Your Data"
                  description="Elastos Decentralized Storage (Hive) is a new architectural model that allows users to ‘own their own data’. With this technology users can now benefit from a powerful line of features including Vault selection, accessibility, data sandboxing and DID integration."
                />
              </div>
            </div>
          </SplitWrap>
        </ContentContainer>

        <BgImgSubscriber
          title="Join the waitlist"
          text="We are currently in Alpha testing"
          bgImg={subscriberbgImg}
          BtnText="Join"
          onClick={() => (window.location.href = "https://www.profile.site")}
        />
        <Footer />
      </main>
    </>
  );
};

export default VerifiedCredentialPage;
