import React from 'react';

import WhiteBoxes from './components/WhiteBoxes';
import Hero from './components/Hero';
import Explain from './components/Explain';
import Technologies from './components/Technologies';
import Features from './components/Features';
import BgImgSubscriber from '../../components/Subscriber/BgImgSubscriber';
import subscriberbgImg from '../../assets/img/subscribers/digialidentity.png';
import SectionBgImg from '../../assets/img/backgrounds/sectionbg.png';

import {
  Navbar,
  Footer,
  Section,
  FooterContainer,
} from '../../components/layout';

const VerifiedCredentialPage = () => {
  return (
    <>
      <Navbar navColor='dark' />
      <main style={{ background: 'white' }}>
        <Hero
          title='A better way to be online'
          intro='Having multiple profiles is messy. Your personal information is copied and stored on every app. Profile gives you total control of your digital world, in one place. Finally unlock the power of your content online.'
        />
        <WhiteBoxes />
        <Technologies />
        <Explain />
        <Section
          containerStyle={{
            background: `url(${SectionBgImg})`,
          }}
          padding='138px 11% 138px'
          bgColor='rgb(76, 111, 255, .8)'
          txtColor='white'
          txtStyle={{
            color: 'white',
            fontSize: '25px',
            lineHeight: '35px',
          }}
          contentText='Centralized social media applications and online platforms exist today because the data generated by users holds immense value. Profile denies such intrusion by permitting users to create their own self-sovereign identities, unlocking platform features such as personal data storage. This is the only platform of its kind in existence today.'
        />
        <Features />
      </main>
      <FooterContainer style={{ marginTop: 150 }}>
        <BgImgSubscriber
          title='Join the waitlist'
          text='We are currently in Alpha testing'
          bgImg={subscriberbgImg}
          BtnText='Join'
        />
        <Footer />
      </FooterContainer>
    </>
  );
};

export default VerifiedCredentialPage;
